### PR TITLE
Addresses most of the node.js issues identified recently

### PR DESCRIPTION
**Pull request by teddziuba**
That ought to fix it.

### CODE REVIEW

**Comment by glenjamin** [comment]
How very helpful.

**Comment by 3rd-Eden** [comment]
lol

**Comment by nodemonkey09** [comment]
I petition to have this reopened and I'll explain why.

You see Ted has never actually contributed anything meaningful to open source, or the community in general. This would actually be his first real contribution, and it would be a shame for it to go to waste. Granted, it replaces your Readme with a snarky comment, and deletes all your JS files, but this is far more than he's ever done before.

This might just be the encouragement Ted needs to go from shitting on other people's hard work, to actually contributing something useful.

Even Zed Shaw contributes, it's time Ted did as well.

**Comment by josegonzalez** [comment]
+1 on re-opening this pull request.

**Comment by teddziuba** [comment]
@nodemonkey09 for what it's worth, when I was 16 I wrote this: http://en.wikipedia.org/wiki/OpenEMR

**Pull request closed without merging**
